modalbuttontext =  "Get a Quote"
company     =   "#title"
fullname    =   ""
slogan      =   ""
logo		=	"logo.png"
emblem		=	""
industry    =   "#ing"
seo         =   "#ers"
years       =   "many years"
building    =   ""
street      =   "#line one"
towncity    =   "#line two"
county      =   "#area"
postcode    =   "#postcode" 
phone       =   "#phone"
mobile      =   "#mobile"
email       =   "#emailaddress"
facebook    =   "#s"
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
tradesmen   =   ""
trustatrader=   ""
bark        =   ""
